import { useState, useEffect, useContext, useRef } from 'react';
import { AuthContext } from '../context/AuthContext';
import axios from 'axios';
import { AlertOctagon, Mic, Camera, FileText, Loader2, PlaySquare } from 'lucide-react';
import { jsPDF } from "jspdf";

const Dashboard = () => {
    const { user } = useContext(AuthContext);
    const [reports, setReports] = useState([]);
    const [loading, setLoading] = useState(true);
    const [recording, setRecording] = useState(false);
    const [uploading, setUploading] = useState(false);
    
    const mediaRecorderRef = useRef(null);
    const audioChunksRef = useRef([]);
    const fileInputRef = useRef(null);
    const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';

    const fetchReports = async () => {
        try {
            const config = { headers: { Authorization: `Bearer ${user.token}` } };
            const { data } = await axios.get(`${API_URL}/api/reports`, config);
            setReports(data);
        } catch (error) {
            console.error("Error fetching reports", error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchReports();
        // eslint-disable-next-line
    }, [user]);

    // Action 1: Trigger SOS
    const handleSOS = () => {
        const trackingLink = `${window.location.origin}/track/${user._id}`;
        const message = `🚨 EMERGENCY SOS 🚨\nI am in danger and need help immediately! Track my LIVE moving location here:\n${trackingLink}`;
        let targetPhone = "";
        if (user && user.emergencyContact) {
            targetPhone = user.emergencyContact.replace(/\D/g, '');
        }
        const whatsappUrl = `https://wa.me/${targetPhone}?text=${encodeURIComponent(message)}`;
        window.open(whatsappUrl, '_blank');
    };

    // Action 2: Secret Record
    const toggleRecording = async () => {
        if (recording) {
            mediaRecorderRef.current.stop();
            setRecording(false);
        } else {
            try {
                const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
                mediaRecorderRef.current = new MediaRecorder(stream);
                
                mediaRecorderRef.current.ondataavailable = (event) => {
                    if (event.data.size > 0) audioChunksRef.current.push(event.data);
                };

                mediaRecorderRef.current.onstop = async () => {
                    const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/webm' });
                    audioChunksRef.current = [];
                    stream.getTracks().forEach(track => track.stop()); // stop mic
                    await uploadEvidence(audioBlob, 'Secret Audio Recording', 'audio.webm');
                };

                mediaRecorderRef.current.start();
                setRecording(true);
            } catch (err) {
                alert("Microphone access denied or unavailable.");
            }
        }
    };

    // Action 3: Quick Snap
    const handleFileChange = async (e) => {
        const file = e.target.files[0];
        if (file) {
            await uploadEvidence(file, 'Quick Photo Evidence', file.name);
        }
    };

    const uploadEvidence = async (fileBlob, contentText, filename) => {
        setUploading(true);
        try {
            const formData = new FormData();
            formData.append('content', contentText);
            formData.append('platform', 'Direct Action');
            // Mock severity for quick actions
            formData.append('severity', 'High');
            formData.append('aiScore', 95);
            
            // Append file
            formData.append('evidence', fileBlob, filename);

            const config = { 
                headers: { 
                    Authorization: `Bearer ${user.token}`,
                    'Content-Type': 'multipart/form-data'
                } 
            };
            await axios.post(`${API_URL}/api/reports`, formData, config);
            await fetchReports(); // refresh timeline
        } catch (error) {
            console.error("Upload error details:", error.response || error);
            alert(`Upload failed: ${error.response?.data?.message || error.message || "Unknown error"}`);
        } finally {
            setUploading(false);
        }
    };

    // Action 4: Master FIR
    const generateMasterPDF = () => {
        if (reports.length === 0) return alert("No evidence found to compile.");
        const doc = new jsPDF();
        
        doc.setFontSize(22);
        doc.setTextColor(225, 29, 72);
        doc.text("Raksha: Master Evidence Log (FIR Copy)", 20, 20);
        
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        doc.text(`Generated By: ${user.name} (${user.email})`, 20, 30);
        doc.text(`Date of Compilation: ${new Date().toLocaleString()}`, 20, 36);
        
        doc.setLineWidth(0.5);
        doc.line(20, 40, 190, 40);
        
        let currentY = 50;
        
        reports.slice(0, 5).forEach((r, idx) => {
            if (currentY > 250) {
                doc.addPage();
                currentY = 20;
            }
            doc.setFont("helvetica", "bold");
            doc.text(`Incident #${idx + 1}: ${new Date(r.createdAt).toLocaleString()}`, 20, currentY);
            currentY += 6;
            
            doc.setFont("helvetica", "normal");
            doc.text(`Type: ${r.content}`, 20, currentY);
            currentY += 6;
            
            if (r.evidenceUrls && r.evidenceUrls.length > 0) {
                doc.setTextColor(37, 99, 235); // blue link
                doc.text(`Attachment: ${r.evidenceUrls[0]}`, 20, currentY);
                doc.setTextColor(0, 0, 0);
            } else {
                doc.text(`Attachment: None`, 20, currentY);
            }
            currentY += 15;
        });

        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("This master document is auto-generated by the Raksha Action Center.", 20, 280);

        doc.save(`Raksha_Master_FIR.pdf`);
    };

    if (loading) return <div className="p-8 text-center text-slate-800 flex justify-center items-center h-screen"><Loader2 className="animate-spin w-8 h-8" /></div>;

    return (
        <div className="max-w-6xl mx-auto px-4 py-8 w-full bg-transparent min-h-[calc(100vh-80px)] text-slate-200">
            <header className="mb-10 text-center">
                <h1 className="text-5xl font-cursive font-extrabold text-white tracking-widest mb-2 drop-shadow-[0_0_15px_rgba(255,255,255,0.2)]">Action Center</h1>
                <p className="text-slate-400 uppercase tracking-widest text-sm font-bold">One-Tap Emergency Responses & Evidence Collection</p>
            </header>

            {/* The 4 Massive Action Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
                
                {/* 1. SOS */}
                <button onClick={handleSOS} className="group bg-slate-900/40 backdrop-blur-md border border-white/10 hover:border-rose-500/50 hover:bg-rose-950/30 transition-all duration-300 hover:-translate-y-2 shadow-lg hover:shadow-[0_0_30px_rgba(225,29,72,0.4)] flex flex-col items-center justify-center p-8 h-64 rounded-2xl relative overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-b from-rose-500/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                    <AlertOctagon className="w-16 h-16 text-rose-500 mb-4 group-hover:animate-pulse z-10" />
                    <h3 className="text-white font-extrabold text-xl uppercase tracking-widest z-10">Trigger SOS</h3>
                    <p className="text-rose-200/60 text-xs mt-2 text-center uppercase font-bold z-10">Live Track & Alert</p>
                </button>

                {/* 2. Secret Record */}
                <button onClick={toggleRecording} className={`group bg-slate-900/40 backdrop-blur-md border border-white/10 ${recording ? 'border-emerald-500 shadow-[0_0_30px_rgba(16,185,129,0.4)] bg-emerald-950/30' : 'hover:border-emerald-500/50 hover:bg-emerald-950/30 hover:shadow-[0_0_30px_rgba(16,185,129,0.3)] hover:-translate-y-2'} transition-all duration-300 flex flex-col items-center justify-center p-8 h-64 rounded-2xl relative overflow-hidden`}>
                    <div className="absolute inset-0 bg-gradient-to-b from-emerald-500/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                    <Mic className={`w-16 h-16 ${recording ? 'text-emerald-400 animate-pulse' : 'text-emerald-500/80'} mb-4 z-10 transition-colors`} />
                    <h3 className="text-white font-extrabold text-xl uppercase tracking-widest z-10">
                        {recording ? 'Recording...' : 'Secret Audio'}
                    </h3>
                    <p className="text-emerald-200/60 text-xs mt-2 text-center uppercase font-bold z-10">
                        {recording ? 'Tap to Save to Vault' : 'One-Tap Mic Access'}
                    </p>
                </button>

                {/* 3. Quick Snap */}
                <div className="relative group bg-slate-900/40 backdrop-blur-md border border-white/10 hover:border-blue-500/50 hover:bg-blue-950/30 transition-all duration-300 hover:-translate-y-2 shadow-lg hover:shadow-[0_0_30px_rgba(59,130,246,0.4)] flex flex-col items-center justify-center p-8 h-64 rounded-2xl overflow-hidden cursor-pointer">
                    <div className="absolute inset-0 bg-gradient-to-b from-blue-500/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                    <input 
                        type="file" 
                        accept="image/*" 
                        capture="environment"
                        onChange={handleFileChange}
                        disabled={uploading}
                        className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-20"
                    />
                    {uploading ? <Loader2 className="w-16 h-16 text-blue-400 mb-4 animate-spin z-10" /> : <Camera className="w-16 h-16 text-blue-500/80 mb-4 group-hover:scale-110 transition-transform z-10" />}
                    <h3 className="text-white font-extrabold text-xl uppercase tracking-widest z-10">
                        {uploading ? 'Uploading...' : 'Quick Snap'}
                    </h3>
                    <p className="text-blue-200/60 text-xs mt-2 text-center uppercase font-bold z-10">Direct Camera Upload</p>
                </div>

                {/* 4. Auto-FIR */}
                <button onClick={generateMasterPDF} className="group bg-slate-900/40 backdrop-blur-md border border-white/10 hover:border-purple-500/50 hover:bg-purple-950/30 transition-all duration-300 hover:-translate-y-2 shadow-lg hover:shadow-[0_0_30px_rgba(168,85,247,0.4)] flex flex-col items-center justify-center p-8 h-64 rounded-2xl relative overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-b from-purple-500/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                    <FileText className="w-16 h-16 text-purple-500/80 mb-4 group-hover:-translate-y-1 transition-transform z-10" />
                    <h3 className="text-white font-extrabold text-xl uppercase tracking-widest z-10">Auto-FIR</h3>
                    <p className="text-purple-200/60 text-xs mt-2 text-center uppercase font-bold z-10">Compile Evidence PDF</p>
                </button>

            </div>
        </div>
    );
};

export default Dashboard;
