import { useState, useEffect, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import axios from 'axios';
import { FileText, AlertTriangle, CheckCircle, Clock } from 'lucide-react';
import { Link } from 'react-router-dom';
import { jsPDF } from "jspdf";

const Dashboard = () => {
    const { user } = useContext(AuthContext);
    const [reports, setReports] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchReports = async () => {
            try {
                const config = {
                    headers: { Authorization: `Bearer ${user.token}` }
                };
                const { data } = await axios.get(`${import.meta.env.VITE_API_URL || 'http://localhost:5000'}/api/reports`, config);
                setReports(data);
            } catch (error) {
                console.error("Error fetching reports", error);
            } finally {
                setLoading(false);
            }
        };
        fetchReports();
    }, [user]);

    const handleEscalate = async (id) => {
        try {
            const config = { headers: { Authorization: `Bearer ${user.token}` } };
            await axios.post(`${import.meta.env.VITE_API_URL || 'http://localhost:5000'}/api/reports/${id}/escalate`, {}, config);
            alert("Report successfully escalated to designated authorities via encrypted email.");
            // Refresh reports to show escalated status
            setReports(reports.map(r => r._id === id ? { ...r, escalated: true } : r));
        } catch (error) {
            console.error(error);
            alert(error.response?.data?.message || "Failed to escalate report.");
        }
    };

    const generatePDF = (report) => {
        const doc = new jsPDF();
        
        // Header
        doc.setFontSize(22);
        doc.setTextColor(225, 29, 72); // Rose color
        doc.text("SafeHer: Official Incident Report", 20, 20);
        
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.text(`Report ID: ${report._id}`, 20, 30);
        doc.text(`Date Filed: ${new Date(report.createdAt).toLocaleString()}`, 20, 38);
        doc.text(`Status: ${report.escalated ? 'ESCALATED' : 'LOGGED'}`, 20, 46);
        
        // Horizontal Line
        doc.setLineWidth(0.5);
        doc.line(20, 50, 190, 50);
        
        // Details
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Platform / Context:", 20, 60);
        doc.setFont("helvetica", "normal");
        doc.text(report.platform || "Not Specified", 20, 68);

        doc.setFont("helvetica", "bold");
        doc.text("AI Severity Assessment:", 20, 78);
        doc.setFont("helvetica", "normal");
        doc.text(`${report.severity} (${report.aiScore}% Toxicity Metric)`, 20, 86);

        // Content Narrative
        doc.setFont("helvetica", "bold");
        doc.text("Incident Narrative:", 20, 96);
        
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        const splitText = doc.splitTextToSize(report.content, 170);
        doc.text(splitText, 20, 104);
        
        // Evidence Links
        const narrativeHeight = splitText.length * 7;
        let currentY = 104 + narrativeHeight + 10;
        
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Logged Evidence (Cryptographic Links):", 20, currentY);
        
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        currentY += 8;
        
        if (report.evidenceUrls && report.evidenceUrls.length > 0) {
            report.evidenceUrls.forEach((url, i) => {
                doc.text(`Attachment ${i + 1}: ${url}`, 20, currentY);
                currentY += 8;
            });
        } else {
            doc.text("No attachments provided.", 20, currentY);
        }

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("This document is auto-generated by the SafeHer Legal Action Engine.", 20, 280);

        doc.save(`SafeHer_Incident_Report_${report._id}.pdf`);
    };

    if (loading) return <div className="p-8 text-center text-[#615e5f]">Loading your secure dashboard...</div>;

    const highSeverityCount = reports.filter(r => r.severity === 'High').length;

    return (
        <div className="max-w-7xl mx-auto px-4 py-8 w-full bg-transparent min-h-screen text-[#615e5f]">
            <header className="mb-10">
                <h1 className="text-4xl font-cursive font-bold text-[#615e5f] tracking-widest mb-2">Welcome, {user.name}</h1>
                <p className="text-[#615e5f] uppercase tracking-widest text-sm">Your reports are secure and confidential.</p>
            </header>

            <div className="grid md:grid-cols-3 gap-6 mb-12">
                <div className="bg-white border border-gray-700 p-6 rounded-none flex items-center gap-4">
                    <div className="p-4 bg-[#615e5f] text-white hover:bg-[#4a4748]"><FileText /></div>
                    <div>
                        <p className="text-[#615e5f] text-sm font-bold uppercase tracking-widest">Total Reports</p>
                        <h3 className="text-3xl font-extrabold font-sans text-[#615e5f] mt-1">{reports.length}</h3>
                    </div>
                </div>
                <div className="bg-white border border-gray-700 p-6 rounded-none flex items-center gap-4">
                    <div className="p-4 bg-gray-800 text-white"><AlertTriangle /></div>
                    <div>
                        <p className="text-[#615e5f] text-sm font-bold uppercase tracking-widest">High Severity</p>
                        <h3 className="text-3xl font-extrabold font-sans text-[#615e5f] mt-1">{highSeverityCount}</h3>
                    </div>
                </div>
                <div className="bg-white border border-gray-700 p-6 rounded-none flex items-center gap-4">
                    <div className="p-4 bg-[#ffffff]/90 border border-[#c4b7b1] text-[#615e5f]"><CheckCircle /></div>
                    <div>
                        <p className="text-[#615e5f] text-sm font-bold uppercase tracking-widest">Resolved (Mock)</p>
                        <h3 className="text-3xl font-extrabold font-sans text-[#615e5f] mt-1">0</h3>
                    </div>
                </div>
            </div>

            <div className="flex justify-between items-center mb-6 border-b border-[#c4b7b1] pb-4">
                <h2 className="text-2xl font-bold font-cursive tracking-widest">Recent Reports</h2>
                <Link to="/report" className="text-sm bg-[#615e5f] text-white hover:bg-[#4a4748] hover:bg-[#4a4748] border border-[#615e5f] px-4 py-2 rounded-none transition-colors font-bold uppercase tracking-widest">
                    + New Report
                </Link>
            </div>

            {reports.length === 0 ? (
                <div className="bg-white border border-[#c4b7b1] rounded-none p-12 text-center">
                    <img 
                        src="/images/first_image.jpg"
                        alt="No reports" 
                        className="w-32 h-32 object-cover mx-auto mb-6 opacity-80 "
                        onError={(e) => { e.target.style.display = 'none'; }}
                    />
                    <h3 className="text-2xl font-bold text-[#615e5f] mb-2 font-cursive tracking-widest">No Reports Yet</h3>
                    <p className="text-[#615e5f] max-w-sm mx-auto mb-6 text-sm uppercase tracking-widest">You haven't filed any reports. Your dashboard is clear.</p>
                    <Link to="/report" className="inline-block bg-[#615e5f] text-white hover:bg-[#4a4748] hover:bg-[#4a4748] px-6 py-3 rounded-none font-extrabold uppercase tracking-widest border-2 border-[#615e5f] transition-colors">
                        File a Report
                    </Link>
                </div>
            ) : (
                <div className="bg-white border border-gray-700 rounded-none overflow-hidden">
                    <div className="overflow-x-auto">
                        <table className="w-full text-left text-sm text-[#615e5f]">
                            <thead className="text-xs text-[#615e5f] uppercase tracking-widest bg-[#ffffff]/90 border-b border-gray-700">
                                <tr>
                                    <th className="px-6 py-4">Date</th>
                                    <th className="px-6 py-4">Platform</th>
                                    <th className="px-6 py-4">Severity</th>
                                    <th className="px-6 py-4">Status</th>
                                    <th className="px-6 py-4 text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {reports.map((report) => (
                                    <tr key={report._id} className="border-t border-[#c4b7b1] hover:bg-[#ffffff]/90/50 transition-colors">
                                        <td className="px-6 py-4 flex items-center gap-2 text-[#615e5f]">
                                            <Clock className="w-4 h-4 text-[#615e5f]" />
                                            {new Date(report.createdAt).toLocaleDateString()}
                                        </td>
                                        <td className="px-6 py-4 font-bold uppercase tracking-widest">{report.platform || 'General'}</td>
                                        <td className="px-6 py-4">
                                            <span className="px-3 py-1 rounded-none text-xs font-bold uppercase tracking-widest border border-gray-600 bg-gray-800 text-white">
                                                {report.severity}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-[#615e5f] uppercase tracking-widest text-xs font-bold">
                                            {report.escalated ? <span className="text-rose-600">Escalated</span> : 'Under Review'}
                                        </td>
                                        <td className="px-6 py-4 text-right space-x-2">
                                            <button 
                                                onClick={() => generatePDF(report)}
                                                className="text-xs bg-[#615e5f] text-white px-3 py-1.5 hover:bg-[#4a4748] transition-colors font-bold uppercase tracking-widest"
                                            >
                                                PDF
                                            </button>
                                            {!report.escalated && (
                                                <button 
                                                    onClick={() => handleEscalate(report._id)}
                                                    className="text-xs bg-rose-600 text-white px-3 py-1.5 hover:bg-rose-700 transition-colors font-bold uppercase tracking-widest"
                                                >
                                                    Escalate
                                                </button>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Dashboard;
